### ISSUE TITLE
I dont star lol

### ISSUE THREAD

**Issue by Hymerine** [Heashey/Self-Leak---Avalanche-Valorant-External#1]
Its not even working after I updated it so I dont star lmao

**Comment by Heashey-zz** [comment]
how exactly did you update it then lmao

**Comment by Hymerine** [comment]
Updated structs and offsets lmao

**Comment by Heashey-zz** [comment]
okay? and what driver are you using

**Comment by Hymerine** [comment]
uefi driver and it inject and I can use the menu but nothing is working

**Comment by Heashey-zz** [comment]
that literally means the offsets are wrong..
